name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/my-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Harness CLI
      run: |
        curl -L https://app.harness.io/public/shared/tools/cli/harness-cli-linux-amd64 -o harness
        chmod +x harness
        sudo mv harness /usr/local/bin/

    - name: Deploy to AWS ASG using Harness
      env:
        HARNESS_ACCOUNT_ID: ${{ secrets.HARNESS_ACCOUNT_ID }}
        HARNESS_API_KEY: ${{ secrets.HARNESS_API_KEY }}
        HARNESS_APPLICATION_ID: ${{ secrets.HARNESS_APPLICATION_ID }}
        HARNESS_SERVICE_ID: ${{ secrets.HARNESS_SERVICE_ID }}
        HARNESS_ENVIRONMENT_ID: ${{ secrets.HARNESS_ENVIRONMENT_ID }}
        HARNESS_WORKFLOW_ID: ${{ secrets.HARNESS_WORKFLOW_ID }}
      run: |
        harness login --account-id $HARNESS_ACCOUNT_ID --api-key $HARNESS_API_KEY
        harness deploy --app-id $HARNESS_APPLICATION_ID --service-id $HARNESS_SERVICE_ID --env-id $HARNESS_ENVIRONMENT_ID --workflow-id $HARNESS_WORKFLOW_ID
